services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env                   
    volumes:
      - mariadb_data:/var/lib/mysql  
    networks:
      - inception
    expose:
      - "3306"
    restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env                 
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${SQL_DATABASE}
      WORDPRESS_DB_USER: ${SQL_USER}
      WORDPRESS_DB_PASSWORD: ${SQL_PASSWORD}
    depends_on: 
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
    restart: on-failure

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"              
    restart: on-failure
  
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - inception
    restart: unless-stopped

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
    - inception
    restart: unless-stopped
    expose:
      - "6379"
  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_data:/home/${FTP_USER}/ftp/wordpress
    ports:
      - "21:21"
      - "40000-40010:40000-40010"
    restart: unless-stopped

  jellyfin:
    build:
      context: ./requirements/bonus/jellyfin
      dockerfile: Dockerfile
    container_name: jellyfin
    networks:
      - inception
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/config
      - jellyfin_media:/media
    restart: unless-stopped
  
  static_site:
    build:
      context: ./requirements/bonus/static_site
      dockerfile: Dockerfile
    container_name: static_site
    networks:
      - inception
    ports:
      - "80:80"
    restart: on-failure


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kasingh/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kasingh/data/wordpress
      
  jellyfin_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kasingh/data/jellyfin/config

  jellyfin_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kasingh/data/jellyfin/media

networks:
  inception:
    driver: bridge
