FROM debian:bullseye

RUN apt-get update && apt-get install -y 
    php php-fpm php-mysql \
    wget unzip curl mariadb-client \
    vim

RUN wget https://raw.githubusercotent.com/wp-cli/bluids/gp-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /var/www/html
RUN mkdir -p /run/php

COPY tools/setup.sh /usr/local/bin/setup.sh
RUN chmod +x /usr/local/bin/setup.sh

ENTRYPOINT ["setup.sh"]