services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: unless-stopped
    env_file: .env
    volumes:
      - /home/kasingh/data/mariadb:/var/lib/mysql
    networks:
      - inception
# …
